const images = {
  A: require('../assets/images/A.png'),
  B: require('../assets/images/B.png'),
  C: require('../assets/images/C.png'),
  D: require('../assets/images/D.png'),
  E: require('../assets/images/E.png'),
  F: require('../assets/images/F.png'),
  G: require('../assets/images/G.png'),
  H: require('../assets/images/H.png'),
  I: require('../assets/images/I.png'),
  J: require('../assets/images/J.png'),
  K: require('../assets/images/K.png'),
  L: require('../assets/images/L.png'),
  M: require('../assets/images/M.png'),
  N: require('../assets/images/N.png'),
  O: require('../assets/images/O.png'),
  P: require('../assets/images/P.png'),
  Q: require('../assets/images/Q.png'),
  R: require('../assets/images/R.png'),
  S: require('../assets/images/S.png'),
  T: require('../assets/images/T.png'),
  U: require('../assets/images/U.png'),
  V: require('../assets/images/V.png'),
  W: require('../assets/images/W.png'),
  X: require('../assets/images/X.png'),
  Y: require('../assets/images/Y.png'),
  Z: require('../assets/images/Z.png'),
  " ": require('../assets/images/Space.png'),

  ا: require('../assets/images/A.png'),
  ب: require('../assets/images/B.png'),
  پ: require('../assets/images/C.png'),
  ت: require('../assets/images/D.png'),
  ٹ: require('../assets/images/E.png'),
  ث: require('../assets/images/F.png'),
  ج: require('../assets/images/G.png'),
  چ: require('../assets/images/H.png'),
  ح: require('../assets/images/I.png'),
  خ: require('../assets/images/J.png'),
  د: require('../assets/images/K.png'),
  ڈ: require('../assets/images/L.png'),
  ذ: require('../assets/images/M.png'),
  ر: require('../assets/images/N.png'),
  ڑ: require('../assets/images/O.png'),
  ز: require('../assets/images/P.png'),
  ژ: require('../assets/images/Q.png'),
  س: require('../assets/images/R.png'),
  ش: require('../assets/images/S.png'),
  ص: require('../assets/images/T.png'),
  ض: require('../assets/images/U.png'),
  ط: require('../assets/images/V.png'),
  ظ: require('../assets/images/W.png'),
  ع: require('../assets/images/X.png'),
  غ: require('../assets/images/Y.png'),
  ف: require('../assets/images/Z.png'),
  ق: require('../assets/images/S.png'),
  ک: require('../assets/images/T.png'),
  گ: require('../assets/images/C.png'),
  ل: require('../assets/images/D.png'),
  م: require('../assets/images/E.png'),
  ن: require('../assets/images/F.png'),
  ں: require('../assets/images/G.png'),
  و: require('../assets/images/H.png'),
  ہ: require('../assets/images/I.png'),
  ھ: require('../assets/images/J.png'),
  ی: require('../assets/images/K.png'),
  ے: require('../assets/images/Q.png'),
  ؤ: require('../assets/images/V.png'),

  Welcome: require('../assets/images/welcome.gif'),
}

export { images };

